In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("/content/ecommerce_messy_dataset.csv")

In [ ]:
df

,Order_ID,Order_Date,Customer_ID,Gender,Age,City,Product_Category,Product_Name,Price,Quantity,Payment_Method
0,ORD10000,2024-01-29,CUST1430,Female,56.0,Delhi,Clothing,NaN,4003.06,3.0,Cash
1,ORD10001,2022-03-03,CUST1761,Male,25.0,kolkata,Clothing,Lipstick,3033.43,2.0,NaN
2,ORD10002,2023-09-11,CUST1371,Other,36.0,Mumbai,NaN,Lipstick,589.88,3.0,Cash
3,ORD10003,2024-03-16,CUST1434,Other,41.0,Hyderabad,Sports,Dress,1735.17,3.0,Cash
4,NaN,2023-05-04,CUST1532,Female,39.0,kolkata,Beauty,Dress,376.42,4.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
5195,ORD10469,2023-01-23,CUST1172,M,34.0,Hyderabad,NaN,Dress,401.43,5.0,UPI
5196,ORD13297,2022-02-26,CUST1554,NaN,19.0,Hyderabad,NaN,Headphones,2897.86,5.0,Debit Card
5197,ORD14756,2023-09-12,CUST1566,M,55.0,NaN,Home,Laptop,2156.39,1.0,NaN
5198,ORD13192,2022-03-09,CUST1019,NaN,18.0,Bangalore,Electronics,Headphones,4952.09,5.0,Debit Card
5199,ORD13246,2024-05-28,CUST1298,Other,28.0,Delhi,Clothing,Laptop,3566.92,3.0,Credit Card

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5200 entries, 0 to 5199
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          5084 non-null   object
 1   Order_Date        4957 non-null   object
 2   Customer_ID       5140 non-null   object
 3   Gender            4311 non-null   object
 4   Age               5077 non-null   float64
 5   City              4567 non-null   object
 6   Product_Category  4316 non-null   object
 7   Product_Name      4497 non-null   object
 8   Price             5051 non-null   float64
 9   Quantity          4318 non-null   float64
 10  Payment_Method    4192 non-null   object
dtypes: float64(3), object(8)
memory usage: 447.0+ KB

In [ ]:
df.isnull().sum()

Order_ID             116
Order_Date           243
Customer_ID           60
Gender               889
Age                  123
City                 633
Product_Category     884
Product_Name         703
Price                149
Quantity             882
Payment_Method      1008
dtype: int64

In [ ]:
df.describe()

               Age        Price     Quantity
count  5077.000000  5051.000000  4318.000000
mean     38.347646  2560.201924     2.997453
std      11.950692  1418.007295     1.430740
min      18.000000   100.060000     1.000000
25%      28.000000  1337.260000     2.000000
50%      38.000000  2578.850000     3.000000
75%      48.000000  3786.705000     4.000000
max      59.000000  4999.260000     5.000000

In [ ]:
df=df.dropna(subset=['Order_ID'])

In [ ]:
df.isnull().sum()

Order_ID             116
Order_Date           243
Customer_ID           60
Gender               889
Age                  123
City                 633
Product_Category     884
Product_Name         703
Price                149
Quantity             882
Payment_Method      1008
dtype: int64

In [ ]:
categorical=['Gender','City','Product_Category','Payment_Method']

for i in categorical:
   df[i].fillna("Unknown",inplace=True)

/tmp/ipykernel_9451/3390499143.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[i].fillna("Unknown",inplace=True)
/tmp/ipykernel_9451/3390499143.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i].fillna("Unknown",inplace=True)

In [ ]:
a=[1,2,3,4,5]
for i in a:
  print(i)

1
2
3
4
5

In [ ]:
df.isnull().sum()

Order_ID              0
Order_Date          230
Customer_ID          60
Gender                0
Age                 123
City                  0
Product_Category      0
Product_Name        693
Price               146
Quantity            863
Payment_Method        0
dtype: int64

In [ ]:
#df['Age'].fillma(df['Age'].median=True)
#df['Quantity'].fillma(df['Age'].median=True)
#df['Price'].fillma(df['Age'].median=True)

In [ ]:
numerical=["Age","Price","Quantity"]

for i in numerical:
  df[i].fillna(df[i].median(),inplace=True)

/tmp/ipykernel_9451/2291400630.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[i].fillna(df[i].median(),inplace=True)
/tmp/ipykernel_9451/2291400630.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i].fillna(df[i].median(),inplace=True)

In [ ]:
df.isnull().sum()

Order_ID              0
Order_Date          230
Customer_ID          60
Gender                0
Age                   0
City                  0
Product_Category      0
Product_Name        693
Price                 0
Quantity              0
Payment_Method        0
dtype: int64

In [ ]:
df=df.dropna(subset=['Customer_ID'])

In [ ]:
df["Gender"].unique()

array(['Female', 'Male', 'Other', 'M', 'Unknown', 'F'], dtype=object)

In [ ]:
df['Gender']=df['Gender'].fillna({'M':'Male','F':'Female'})

In [ ]:
df['City'].unique()

array(['Delhi', 'kolkata', 'Mumbai', 'Hyderabad', 'Unknown', 'Kolkata',
       'Bangalore', 'Chennai'], dtype=object)

In [ ]:
df['Order_Date']=pd.to_datetime(df['Order_Date'])

In [ ]:
df['Order_Date'].fillna(method='ffill',inplace=True)

/tmp/ipykernel_9451/4168281717.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Order_Date'].fillna(method='ffill',inplace=True)
/tmp/ipykernel_9451/4168281717.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Order_Date'].fillna(method='ffill',inplace=True)

In [ ]:
df.isnull().sum()

Order_ID              0
Order_Date            0
Customer_ID           0
Gender                0
Age                   0
City                  0
Product_Category      0
Product_Name        687
Price                 0
Quantity              0
Payment_Method        0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5024 entries, 0 to 5199
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          5024 non-null   object
 1   Order_Date        5024 non-null   datetime64[ns]
 2   Customer_ID       5024 non-null   object
 3   Gender            5024 non-null   object
 4   Age               5024 non-null   float64
 5   City              5024 non-null   object
 6   Product_Category  5024 non-null   object
 7   Product_Name      4337 non-null   object
 8   Price             5024 non-null   float64
 9   Quantity          5024 non-null   float64
 10  Payment_Method    5024 non-null   object
dtypes: datetime64[ns](1), float64(3), object(7)
memory usage: 471.0+ KB

In [ ]:
df['Total']=df['Price']*df['Quantity']